### ISSUE TITLE
Situation « Contrôle » : détecter dans quel bac une pièce a été posée

### ISSUE THREAD

**Issue by egaillot** [betagouv/competences-pro#105]
Quand une pièce disparaît, on veut pouvoir détecter si elle a été posée dans le bon bac, et indiquer au journal quel élément enregistrer.

Proposition de solution : 
- `VueSituation` maintient la liste des `Bac` instanciés
- à chaque création d'une `Piece`, `VueSituation` s'abonne à cette pièce
- lorsque la pièce disparaît, elle notifie ses abonnés
- lorsque `VueSituation` est notifiée de la disparition d'une pièce, elle appelle chaque `Bac` et lui demande de déterminer s'il contient la pièce en question, et s'il est le bon bac pour cette pièce
- si un `Bac` répond « oui » aux deux questions, alors `VueSituation` demande à `Journal` d'enregistrer un `EvenementPieceBienPlacee` – et un `EvenementPieceMalPlacee` dans le cas contraire

Pour cela il faut :
- [x] Faire en sorte que `VueSituation` se rappelle la liste des `Bac` instanciés
- [x] Abonner `VueSituation` à chaque création d'une nouvelle pièce
- [x] Notifier les abonnés à chaque disparition d'une pièce
- [ ] Faire en sorte que `Piece` connaisse ses dimensions
- [x] Implémenter `Bac#contient(piece)`
- [ ] Implémenter `Bac#estDeLaBonneCategoriePour(piece)`
- [x] Ajouter `EvenementPieceBienPlacee`
- [x] Ajouter `EvenementPieceMalPlacee`
- [ ] Implémenter `VueSituation#verifiePieceBienPlacee(piece)`

**Comment by francois2metz** [comment]
Je ne sais pas forcément comment l'exprimer, mais je connais un peu l'api drag'n drop et je sais que l'on peut écouter un événement *drop*. L'écoute de cet événement sur les bacs pourrait simplifier une ou plusieurs étapes que tu a listé.
