### ISSUE TITLE
[Inventaire] Intégrer la modale de fin

### ISSUE THREAD

**Issue by morissetcl** [betagouv/competences-pro#127]
Aprés confirmation de Thibaut voici le bon design:

![08_VérificationToutbon](https://user-images.githubusercontent.com/20596535/55393146-f64ab280-553c-11e9-875d-e81549b8d855.png)

**Comment by etienneCharignon** [comment]
Attention, il y a deux modales proposé pour le cas succès et il ne me semble pas que la décision a été prise entre les deux proposition.
![08_VérificationToutbon](https://user-images.githubusercontent.com/298214/55334851-5e948800-549a-11e9-8649-0b1f2354fba2.png)

**Comment by morissetcl** [comment]
Ok my bad, je suis dans l'attente d'une réponse dans le channel design.
