### ISSUE TITLE
[Contrôle] Implémenter la séquence de biscuits

### ISSUE THREAD

**Issue by shanser** [betagouv/competences-pro#148]
La mise en situation prévoit 60 biscuits qui apparaissent dans un ordre défini avec des défauts fixes.
La séquence totale décrite dans ce fichier : https://docs.google.com/spreadsheets/d/1NzAtWAvsEzax-P_bWA83PpveAVGA_sS1Elkgad0PYrI/edit#gid=362726602

- [x] affichait les pieces dans l'ordre dit
- [ ] avoir le bon délai d'apparition pour chaque piece

biscuit n°1 | bon
-- | --
biscuit n°2 | bon
biscuit n°3 | bon
biscuit n°4 | def15
biscuit n°5 | bon
biscuit n°6 | bon
biscuit n°7 | def3
biscuit n°8 | bon
biscuit n°9 | bon
biscuit n°10 | bon
biscuit n°11 | def5
biscuit n°12 | bon
biscuit n°13 | def11
biscuit n°14 | bon
biscuit n°15 | def2
biscuit n°16 | bon
biscuit n°17 | def14
biscuit n°18 | bon
biscuit n°19 | bon
biscuit n°20 | bon
biscuit n°21 | def13
biscuit n°22 | bon
biscuit n°23 | bon
biscuit n°24 | bon
biscuit n°25 | bon
biscuit n°26 | def16
biscuit n°27 | bon
biscuit n°28 | bon
biscuit n°29 | def12
biscuit n°30 | bon
biscuit n°31 | bon
biscuit n°32 | bon
biscuit n°33 | bon
biscuit n°34 | bon
biscuit n°35 | def2
biscuit n°36 | bon
biscuit n°37 | def13
biscuit n°38 | bon
biscuit n°39 | def16
biscuit n°40 | def14
biscuit n°41 | bon
biscuit n°42 | def13
biscuit n°43 | bon
biscuit n°44 | bon
biscuit n°45 | def5
biscuit n°46 | bon
biscuit n°47 | def15
biscuit n°48 | bon
biscuit n°49 | bon
biscuit n°50 | def11
biscuit n°51 | bon
biscuit n°52 | bon
biscuit n°53 | bon
biscuit n°54 | bon
biscuit n°55 | bon
biscuit n°56 | def5
biscuit n°57 | def3
biscuit n°58 | bon
biscuit n°59 | def3
biscuit n°60 | bon

**Comment by francois2metz** [comment]
Je ferme pour mettre le deuxième point dans une issue a part #273
