### ISSUE TITLE
Pouvoir rentrer son nom (ou pseudo)

### ISSUE THREAD

**Issue by francois2metz** [betagouv/competences-pro#155]
Pour les tests, on va avoir besoin d'identifier qui a fait quoi. Avec les sessions actuelles, difficile de le savoir.

Il faut qu'on demande une information tel que son nom a l'utilisateur-trice pour ensuite l'incorporer dans les événements.

Comme contrainte il faut aussi pouvoir distinguer les différents essai de situation (et garder donc le session_id il me semble).

**Comment by etienneCharignon** [comment]
Je verrais bien ça dans la page d'accueil.
