### ISSUE TITLE
Regrouper l'initialisation de toutes les ressources audios

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/competences-pro#192]
Plutôt que d'initialiser les ressources audios dans chanque modèle de situation, on voudrait regrouper toutes ces initilisations dans un seul fichier `commun/modèles/audios.js` sur le même modèles que les ressources d'internationalisation `locales/fr.json`

Ce fichier javascript initialiserait toutes les ressources audio de toutes les situations. Il serait ensuite possible de demander une ressource en suivant un chemin du type :  `audios.controle.consigne` ou `audios.inventaire.consigne` par exemple.

**Comment by francois2metz** [comment]
Pas d'activité sur ce sujet depuis un bon moment. Je ferme.
