### ISSUE TITLE
[Controle et Tri] Gérer les touch events pour le drag'n drop

### ISSUE THREAD

**Issue by francois2metz** [betagouv/competences-pro#206]
Pour que cela fonctionne sur tablettes aussi.

**Comment by etienneCharignon** [comment]
Cette issue qui a été commencée est mise en pause pour traiter les issues prioritaires pour le mercredi 28 août.

**Comment by etienneCharignon** [comment]
Pour mémoire, voir le status d'avancement de Manu épinglé sur slack.
