### ISSUE TITLE
Rajouter un player pour la relecture de la consigne

### ISSUE THREAD

**Issue by morissetcl** [betagouv/competences-pro#235]
- [ ] ajouter le bouton stop (pour stopper la relecture de la consigne), à la place du bouton attente avec les 3 petits points
- [ ] ajouter le curseur ("slider") permettant d'aller directement à un endroit précis de la consigne.

**Comment by etienneCharignon** [comment]
On attend pour l'instant car il y a un impact avec la consigne textuelle (pour les malentendants)

**Comment by francois2metz** [comment]
Ce n'est plus a l'ordre du jour pour le moment.
