### ISSUE TITLE
Permettre à l'utilisateur de rejouer la consigne avant de cliquer sur le bouton GO

### ISSUE THREAD

**Issue by morissetcl** [betagouv/competences-pro#236]
<img width="557" alt="Screenshot 2019-05-15 at 16 32 50" src="https://user-images.githubusercontent.com/86659/57864759-c3aefd80-77fc-11e9-8832-baf847e5773a.png">

**Comment by etienneCharignon** [comment]
Suite à la réunion en visio du 07/05, on attend d'avoir une proposition UX pour implémenter cette fonctionnalité

**Comment by francois2metz** [comment]
J'ai mis à jour la description avec la maquette
