### ISSUE TITLE
Problème: La relecture de la consigne est inaudible dans la situation Contrôle

### ISSUE THREAD

**Issue by morissetcl** [betagouv/competences-pro#237]

**Comment by etienneCharignon** [comment]
Comme discuté le mardi 07/05 en visio d'équipe, on peut essayer de simplement baisser le niveau sonore du tapis sur tout la durée de la situation et voir dans un deuxième temps si on peut avoir un tapis très bruyant sauf pendant la lecture de la consigne où on baisserait son volume sonore pour pouvoir entendre la consigne.
