### ISSUE TITLE
Si on écoute la consigne au démarrage et qu'on la réécoute ensuite via le bouton dédié, à la fin de la réécoute, le bouton go apparait

### ISSUE THREAD

**Issue by francois2metz** [betagouv/competences-pro#241]
On s'attendrait à ce que la vue go n’apparaisse pas

**Comment by etienneCharignon** [comment]
Je ne reproduit pas ce problème sur `master` est-ce que ce bug est toujours d'actualité ?

**Comment by etienneCharignon** [comment]
Le message se termine en indiquant de cliquer sur go. Est-ce que c'est un problème lors du rejoue de la consigne ?

**Comment by francois2metz** [comment]
> Je ne reproduit pas ce problème sur `master` est-ce que ce bug est toujours d'actualité ?

oui

**Comment by francois2metz** [comment]
> Le message se termine en indiquant de cliquer sur go. Est-ce que c'est un problème lors du rejoue de la consigne ?

Je me suis posé la même question.
