### ISSUE TITLE
[Inventaire] Pouvoir accéder aux boutons de commande quand un contenant est ouvert

### ISSUE THREAD

**Issue by egaillot** [betagouv/competences-pro#304]
Quand un contenant est ouvert et qu'on clique sur le bouton « répéter la consigne », la consigne n'est pas jouée et le contenant se referme.

Ce comportement n'est ni intuitif, ni cohérent avec ce qu'il se passe quand le formulaire de saisie d'inventaire est ouvert (où là, la consigne est bien jouée, comme on pourrait s'y attendre).

Suggestion de correction : utiliser un overlay invisible avec la classe `hors-actions` (cf. ce qui est fait pour permettre de répéter la consigne avant de cliquer sur Go).

**Comment by francois2metz** [comment]
Je pense qu'il faudrait plutôt corriger l'implémentation de la classe `calque` pour ne pas être en position `fixed`, mais `absolute`, et en valeur `100%` plutôt que prendre la taille du viewport.
