### ISSUE TITLE
[Inventaire] déplacer les coches vertes sur le formulaire de saisie final

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/competences-pro#333]
⚠️ attention, les produits ne sont pas dans l'ordre sur cette image :
⚠️ Attention à ce que la croix de fermeture ne soit pas présente sur cet écran.

![09_VérificationToutbon](https://user-images.githubusercontent.com/298214/59195776-1c1fb380-8b8d-11e9-9977-26fd57e735b5.png)

**Comment by francois2metz** [comment]
Mergé dans  #332
