### ISSUE TITLE
[Contrôle] aligner la taille des biscuits du tapis sur la taille du modèle

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/competences-pro#334]
Certaines personnes ont classé les biscuits dans "non conforme" parce qu'il n'avait pas exactement la même taille.

En alignant les tailles il ne devrait plus y avoir de problème.

**Comment by egaillot** [comment]
Ce n'est pas clair pour moi… S'agit-il de diminuer la taille des biscuits sur le tapis roulant, ou d'augmenter la taille du biscuit modèle ?

**Comment by etienneCharignon** [comment]
L'idée est de faire au plus simple. Il y a cet argument qu'on voudrait afficher les biscuits en assez grand mais la différence de taille n'est pas très importante et l'une ou l'autre des options devrait convenir. Mon jugement personnel c'est qu'il est plus facile de changer la taille des biscuits sur le tapis (on a déjà le mécanisme pour calculer leur taille il me semble).
