### ISSUE TITLE
Journaliser les événements de la situation stock

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/competences-pro#43]
Nous journalisons déjà les ouvertures de contenant. Il faudrait aussi journaliser les informations suivantes :

- [X] démarrage du test
- [x] appui sur stop
- [X] ouverture de la fiche saisie inventaire : journaliser la date
- [X] validation de la fiche saisie inventaire : journaliser la date, les quantités saisies et le succès/ko
- [x] ouverture d'un contenant : journaliser l'id du contenant plutôt que toute l'information du contenu

**Comment by francois2metz** [comment]
- [X] démarrage du test
- [ ] appui sur stop
- [ ] ouverture de la fiche saisie inventaire : journaliser la date
- [ ] validation de la fiche saisie inventaire : journaliser la date, les quantités saisies et le succès/ko
- [ ] ouverture d'un contenant : journaliser l'id du contenant plutôt que toute l'information du contenu
