### ISSUE TITLE
Créer une adresse email de support.

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/competences-pro#441]
Quelques infos données par Beta.gouv sur le sujet :

https://github.com/betagouv/beta.gouv.fr/wiki/Infra#recommandation-dh%C3%A9bergement-dns-et-emails-pour-un-sous-domaine-betagouvfr

Quelques recommandations reçues de beta.gouv :
- La solution française la plus simple : AlwaysData
- Si tu es connaisseur : tu héberges toi même le serveur DNS et email
- Si tu utilises un hébergement américain : AWS

**Comment by francois2metz** [comment]
C'est fait.
