### ISSUE TITLE
Mode entrainement de la situation sécurité

### ISSUE THREAD

**Issue by francois2metz** [betagouv/competences-pro#511]
- [x] Avoir une vue go différente
- [x] Avoir la situation en mode entrainement
  - [x] rendre le fond entrainement
  - [x] avoir les bonnes zones
  - [x] passer l'état en mode entrainement terminé
- [x] Avoir la vue modal une fois l'entrainement terminé
- [x] reset les dangers identifiés une fois entraînement terminé
- [x] Cacher le bouton rejouer la consigne une fois entraînement terminé
- [x] Affiche le bouton stop pendant entraînement
- [x] Cacher l'aide en mode entraînement
- [x] Envoi un événement au démarrage de entraînement

**Comment by etienneCharignon** [comment]
Pour mémoire : j'ajoute ici les proposition de qualifications : 
- La ceinture de la passagère n’est pas attachée
- La vitre est ouverte
- L’appui-tête est mal réglé du côté passager
