### ISSUE TITLE
La sécurité ne doit pas bloquer si on abandonne pendant l'entrainement

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/competences-pro#572]

**Comment by morissetcl** [comment]
Avec l'entrainement j'ai du mal à voir quand est-ce que l'on souhaite qu'une situation débute ?

Quand on est dans l'entrainement on a le bouton `quitter la mission`..ce qui induit que l'on a commencé la mission (sachant que l'on a déja cliqué sur un bouton `commencer la situation Sécurité`). Sauf que l'on a pas encore envoyé l'événement de démarrage au serveur.

Je ne sais pas si il y a un problème de wording mais pour moi il y a une inconnue/incompréhension de ce que l'on souhaite. 

Je suis preneur d'un éclaircissement/avis.

**Comment by francois2metz** [comment]
Le rajout de entraînement a créé ce problème. Il était inattendu que l'abandon de la sécurité pendant entraînement ne permette pas d'avancer dans l'évaluation contrairement aux autre situations.
