### ISSUE TITLE
Titre du PDF de restitution / Titre de la restitution globale

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/competences-pro#595]
Le titre du PDF de restitution était le suivant : 

"Classement de vos compétences Compétence pro"

Ce titre permettait de parler à l'utilisateur pour lui indiquer qu'on allait lui présenter une restitution de ses compétences telle qu'évalué par l'outil, classée par ordre de "force". On avait ajouté un sous titre "(de la plus forte à la moins forte)" pour rendre plus explicite le sens du classement.

Suite au renommage de "Compétence pro" en "eva", le titre est devenu 

"Classement de vos compétences eva"

Ce qui était devenu beaucoup moins clair en terme de sens (sans doute du à l'absence de majuscule dans le nom du projet qui ne permet plus de l'identifier comme un nom propre)

Nous avons donc retiré le nom "eva" pour obtenir : 

"Classement de vos compétences"

Mais cette nouvelle formulation ne permet plus de préciser que les compétences ne sont pas des concepts définis de manière générique (officiel ?) mais bien des concepts spécifique au projet avec une définition qui nous est propre et un mode d'évaluation qui lui aussi nous est propre.

**Comment by GaelleOttan** [comment]
ok je propose pour le titre de la partie "Classement de vos compétences évaluées par l'outil eva".
Pour donner un titre au pdf et quelques lignes d'intro ça peut être pas mal, mais auj j'ai peur que ça alourdisse la restitution. 
@alexis tu as un avis? Est ce que tu penses que c'est important de mettre une note particulière?

**Comment by Alexis-Akinyemi** [comment]
"Classement de vos compétences évaluées par l'outil eva" peut vouloir dire que ce sont des compétences génériques, mais qu'il est important pour nous de dire que c'est eva qui permet leur évaluation.  "Classement de vos compétences évaluées dans l'outil eva" peut être plus clair. Je ne suis pas contre plus d'explicitation mais j'ai aussi l'impression que ça alourdisse plus que ça n'éclaircisse. Par exemple : 

**Classement de vos compétences** 
Classement des compétences évaluées dans l'outil eva à partir du meilleur score 

Ca alourdit clairement, mais il y a surement une meilleure alternative si on part sur cette idée de titre/intro

**Comment by etienneCharignon** [comment]
Quand je parlais d'un titre, je parlais d'un titre pour tous le document PDF. Ce que nous sommes en train de discuter, c'est le titre de la section "vos compétences" qui est la première page du PDF. Je me disais qu'on pourrait ajouter une page avant cette page qui contiendrai le titre du PDF et une description de ce qu'il contient (c'est à dire la restitution de l'évaluation faites par eva avec en première partie un classement des compétences évaluées par l'outils puis ensuite la restitutions des évaluations par situation)

**Comment by Alexis-Akinyemi** [comment]
Ah oui oui très bonne idée ! 
On fait un sommaire en fait ? :)

**Comment by GaelleOttan** [comment]
@Alexis-Akinyemi si tu veux on peut en reparler, mais il me semble qu'aujourd'hui ce ne soit pas une bonne idée d'alourdir le doc avec du texte (l'idée de la première page étant justement d'être sythétique et visuelle). Est ce que nommer la section "Classement eva de vos compétences" ça pourrait pas répondre au besoin d'être clair et pas trop générique?

**Comment by Alexis-Akinyemi** [comment]
Oui je comprends tout à fait et 
"Classement eva de vos compétences" convient très bien
