### ISSUE TITLE
Modifier éléments et contenu site vitrine

### ISSUE THREAD

**Issue by telohtrab** [betagouv/competences-pro#597]

**Comment by telohtrab** [comment]
![image](https://user-images.githubusercontent.com/7781917/69965356-5c486900-1514-11ea-94af-bfd7e54e73cb.png)

**Comment by GaelleOttan** [comment]
Intégrer le bouton d'accès à l'app depuis le site vitrine (cf la maquette de benjamin dans l'issue) et faire quelques ajustements de contenus (présents dans le document Drive https://docs.google.com/document/d/1XuLTaA75fnVGtyWWhOTE6vHgVMeZ_kJmrcpPsllcoMg/edit?usp=sharing) et reporté ci dessous:

**Dans la home page**
1. Changer le texte pour
----
Titre: Evaluer en ligne les compétences transversales et valoriser les potentiels

eva est une startup d’état portée par la Direction Interministérielle du Numérique (Dinum) et la Direction Générale des Entreprises et de la Formation Professionnelle (DGEFP) dans le cadre du Plan d’Investissement aux Compétences. 

eva permet de positionner les compétences transversales et cognitives et les savoirs de base des candidats au travers de jeux reproduisant des mises en situations  professionnelles

Icone 1: Détecte les freins d’accès à l’emploi, à la formation et permet de réduire les taux d’abandon en évaluant les savoirs de base et en facilitant les échanges 

Icone 2: Augmente les  opportunités professionnelles (formation et emploi)
 des candidats sans diplôme ou expérience adéquate

Icone 3: Révèle les potentiels  des candidats
en détectant leurs compétences transversales et leur capacité de progression
------
2. Supprimer le bouton "pour quel public" (éventuellement à remplacer par "Qui sommes nous?"

**Créer une nouvelle page Qui sommes nous (à également intégrer dans menu du header)**
Qui sommes nous

Problème 
Pour les personnes ne disposant pas de diplômes, d’expérience professionnelle probante ou pour celles les plus éloignées du marché de l’emploi, l’accès à l’emploi et/ou la formation est un enjeu national. Alors que le CV ne représente que 20% de l’employabilité d’un candidat, l’approche par les compétences cognitives et transversales doit être privilégiée, car elle permet de favoriser l’apprentissage et ouvre aux potentialités.
L’évaluation et la valorisation de ces compétences constitue à ce titre un facteur d’accélération du retour à l’emploi et à la formation. Pourtant aucun outil ne permet facilement, rapidement et de manière ludique de mesurer ces compétences.
Une startup d’état porté par une mission d’intérêt général

Née dans le cadre du Plan d’Investissement aux Compétences, eva est une startup portée par la DINUM (Direction Interministérielle du Numérique)  et financée par la DGEFP (Direction Générale des Entreprises et de la Formation Professionnelle). Notre mission principale est d’offrir un outil permettant d’accélérer l’insertion ou le retour à l’emploi ou à la formation. Pour ce faire, eva évalue les compétences transversales/ cognitives les plus recherchées pour les métiers peu qualifiés et valorise le potentiel des candidats plutôt que les compétences métiers et l’employabilité immédiate. En privilégiant le ‘faire’ via la mise en situation, eva est accessible aux personnes en situation d’illettrisme et pourrait permettre dans ce cadre, d’être également utilisé comme outil de détection.

**Changer le wording de la page Compétences pour "Compétences évaluées"** (aussi dans le menu)

**Comment by etienneCharignon** [comment]
@GaelleOttan et @telohtrab est-ce qu'on ne voulais pas aussi mettre à jour l'image avec la femme en rouge sur la page d'accueil et sur la page compétences évaluées ?

**Comment by telohtrab** [comment]
Oui tout à fait ! C'est un placeholder qu'il faut remplacer. Dans mon idée
on aurait une illustration ad-hoc de Matthieu pour accompagner les 2
boutons à côté

Le ven. 6 déc. 2019 à 14:07, Étienne Charignon <notifications@github.com> a
écrit :
