### ISSUE TITLE
Stopper la situation lorsque l'utilisateur·trice veut quitter la page en cours de route

### ISSUE THREAD

**Issue by francois2metz** [betagouv/competences-pro#66]
Actuellement, l'utilisateur·trice n'a pas d'avertissement lorsqu'elle·il quitte la page. Du coup on n'aura pas non plus d'événement stop. 

Écouter l'événement `beforeunload ` permettra de fixer cela.

**Comment by etienneCharignon** [comment]
J’ajoue Ici un commentaire de François pour mémoire : « On pourrait écouter l'événement `beforeunload` et si l'état de la situation est `démarré`, alors demande une confirmation »
