### ISSUE TITLE
Ajouter le bouton "rejouer la consigne" dans la vue cadre

### ISSUE THREAD

**Issue by morissetcl** [betagouv/competences-pro#68]
- [x] Ajouter le bouton rejouer la consigne qui rejoue la consigne
 ~~Journaliser l'événement lorsque l'utilisateur rejoue la consigne~~
~~ajoute les labels à côté des boutons consigne et stop dans la barre de contrôle~~
~~Rejouer la consigne accessible avant de cliquer sur GO~~
~~ajouter le player~~

**Comment by etienneCharignon** [comment]
Une demande de Thibaut était d'avoir carrément un lecteur avec un affichage de la progression de lecture, la possibilité d'avancer directement à point précis de la consigne, de l'arrêter à n'importe quel endroit. Peut-être qu'on peut commencer avec juste un bouton "rejouer la consigne" dans un premier temps et ajouter les autres fonctions par la suite, mais j'avais l'impression que ça pouvait être plus intéressant de s'intéresser à la fonction "player" en une seule issue. Qu'en pensez-vous ?

**Comment by francois2metz** [comment]
Une tache a faire dans ce cadre:

- [ ] Journaliser l'événement lorsque l'utilisateur rejoue la consigne

**Comment by morissetcl** [comment]
J'ai l'impression en regardant les maquettes que l'on a seulement un bouton rejouer la consigne..je me demande si le player est toujours d'actualité ?

<img width="956" alt="Capture d’écran 2019-04-01 à 15 12 36" src="https://user-images.githubusercontent.com/20596535/55330192-b5955f80-5490-11e9-8691-c85696053518.png">

**Comment by etienneCharignon** [comment]
Si j'ai bien compris, c'est au moment où tu appuie sur le bouton play que le player apparait :
![05_RelectureConsigne](https://user-images.githubusercontent.com/298214/55334695-0493c280-549a-11e9-8305-daf38b253c20.png)

**Comment by etienneCharignon** [comment]
Notes discutés en réunion de mercredi 24/04 : 

- Priorité au bouton play (sans slider, ni pause mais avec le texte "rejouer la consigne" à coté). On veut surtout savoir si les utilisateurs on besoins de rejouer la consigne.
- Sur la vue contrôle : pour l'instant, on ne coupe pas le son du tapis pour voir s'il y a un problème.
- Rejouer la consigne accessible avant de cliquer sur GO
