### ISSUE TITLE
Intégration UX : Nouveau Bouton consigne et Go

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/competences-pro#78]
Intégration des nouveaux styles de boutons

- [x] intégration du bouton démarrer la consigne
- [ ] intégration du symbol "consigne en cours"
- [x] intégration du bouton Go
- [x] intégration des consignes textuelles

Chaque bouton est associé à un texte dans le bandeau en bas de l'écran.

Voir les illustrations sur le disque partagé dans le répertoire `…/Interface/Thibaut/190313`

**Comment by shanser** [comment]
En plus de cette Todo list :
- [ ] ajouter les consignes textuelles
