### ISSUE TITLE
Intégration UX : création d'une « barre de contrôle » en bas des situations

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/competences-pro#79]
En bas de chaque situation, on retrouve une « sous-barre » contenant toujours les mêmes boutons « stop » et « rejouer la consigne » et aussi certains messages utilisateur.

- [x] Mettre en place la barre de contrôle
- [x] Mettre les nouvelles icônes

**Comment by shanser** [comment]
- [ ] Mettre en place la barre de contrôle
- [ ] Inclure le bouton rejouer la consigne
- [ ] Mettre les nouvelles icônes
